# sample for calling reusable workflow
name: dtool-config-generator-container-image-build-and-test

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    uses: livMatS/dtool-framework-workflows/.github/workflows/dtool-lookup-framework-generic-container-image-build-and-test.yml@master
    with:
      image: jotelha/dtool-config-generator
      service: dtool_config_generator
      docker_file: ./compose/production/dtool_config_generator/Dockerfile
